Repository LizardWi-zard/SignalDocumentBaseManager, pull requests merged in 2023-11, with the labels that each got.

#16 Windows for user authorization and registration. Also simple methods for navigating
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: WPF

#18 Add Validate data
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#19 Registration and authorization added
  SignalDocumentBaseManager/Classes/User.cs
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#25 Basic filters added
  SignalDocumentBaseManager/MainWindow.xaml
Labels: WPF

#27 Developing filter logic
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#26 Developing sorting by types
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#30 Authorization window change
  SignalDocumentBaseManager/MainWindow.xaml
Labels: WPF

#31 Json strings with test data were moved to files
  SignalDocumentBaseManager/Files/DocumentsJsonToParse.txt
  SignalDocumentBaseManager/Files/UsersJsonToParse.txt
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#36 Added sorting by dates
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#37 Scaling and minor changes
  SignalDocumentBaseManager/MainWindow.xaml
Labels: bug, WPF

#39 Filters now capable to work together
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#41 Fixed Sorting Output
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: bug, C#

#46 Window for document add is reworked
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: WPF

#47 Developing other sorting columns
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#48 Logic is separeted from code behind
  SignalDocumentBaseManager/Classes/DataBaseInteracter.cs
  SignalDocumentBaseManager/Classes/DocumentFile.cs
  SignalDocumentBaseManager/Classes/DocumentSorter.cs
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: C#

#50 Types fixed
  SignalDocumentBaseManager/Classes/DocumentSorter.cs
  SignalDocumentBaseManager/MainWindow.xaml.cs
Labels: bug, C#

#51 Developing excel parse
  SignalDocumentBaseManager/Files/excel.xlsx
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
  SignalDocumentBaseManager/SignalDocumentBaseManager.csproj
Labels: C#

#57 Rework project using MVVM pattern
  SignalDocumentBaseManager/App.xaml
  SignalDocumentBaseManager/Classes/DocumentSorter.cs
  SignalDocumentBaseManager/Core/ObservableObject.cs
  SignalDocumentBaseManager/Core/RelayCommand.cs
  SignalDocumentBaseManager/MVVM/View/DocumentExplorerView.xaml
  SignalDocumentBaseManager/MVVM/View/DocumentExplorerView.xaml.cs
  SignalDocumentBaseManager/MVVM/View/SettingsView.xaml
  SignalDocumentBaseManager/MVVM/View/SettingsView.xaml.cs
  SignalDocumentBaseManager/MVVM/ViewModel/DocumentExplorerViewModel.cs
  SignalDocumentBaseManager/MVVM/ViewModel/MainViewModel.cs
  SignalDocumentBaseManager/MVVM/ViewModel/SettingsViewModel.cs
  SignalDocumentBaseManager/MVVM/ViewModel/ViewModelBase.cs
  SignalDocumentBaseManager/MainWindow.xaml
  SignalDocumentBaseManager/MainWindow.xaml.cs
  SignalDocumentBaseManager/SignalDocumentBaseManager.csproj
Labels: WPF, C#

#60 OpenDialog to get right document to parse
  SignalDocumentBaseManager/MVVM/ViewModel/DocumentExplorerViewModel.cs
Labels: WPF, C#
